spring.application.name: sample-api

server:
  port : 8081

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: test_u1
    password: test_u1
    driverClassName: oracle.jdbc.driver.OracleDriver