DROP TABLE USERS;
CREATE TABLE USERS 
(
  "ID" number NOT NULL ENABLE, 
  "NAME" VARCHAR2(100 BYTE), 
  "EMAIL" VARCHAR2(100 BYTE), 
  "STARTDATE" DATE,  
  "LANK" NUMBER,
  CONSTRAINT PK_USERS PRIMARY KEY (ID)
);
